title: Workshop on Serverless Computing
description: CM/IFIP International Middleware Conference, Novemeber 7-11, 2022 in Qu√©bec, Canada

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# permalink: /:title/

url: "https://www.serverlesscomputing.org"
# baseurl: "/serverlesscomputing"

collections:
  papers:
    output: true
  demos:
    output: true
  keynotes:
    output: false

# Add a new scope and a new directory under _papers and _demos for each wosc edition
defaults:
  - scope:
      path: "_papers/wosc7"
      type: papers
    values:
      layout: paper
      permalink: "wosc7/:collection/:title"
  - scope:
      path: "_demos/wosc7"
      type: demos
    values:
      layout: demo
      permalink: "wosc7/:collection/:title"
  - scope:
      path: "_keynotes/wosc7"
      type: keynotes
    values:
      layout: keynote
      permalink: "wosc7/:collection/:title"
  - scope:
      path: "_papers/wosc8"
      type: papers
    values:
      layout: paper
      permalink: "wosc8/:collection/:title"
  - scope:
      path: "_demos/wosc8"
      type: demos
    values:
      layout: demo
      permalink: "wosc8/:collection/:title"
  - scope:
      path: "_keynotes/wosc8"
      type: keynotes
    values:
      layout: keynote
      permalink: "wosc8/:collection/:title"

wosc:
  current_edition: wosc8
  current_edition_number: 8
  links:
    - name: Call for Papers
      relative_url: /cfp
    - name: Accepted papers
      relative_url: /papers
    - name: Demos
      relative_url: /demos
    - name: Invited speakers
      relative_url: /keynotes
    - name: Program
      relative_url: /program
    - name: Previous Editions
      menu:
        - name: 2022 WoSC 8
          relative_url: /wosc8
        - name: 2021 WoSC 7
          relative_url: /wosc7
        - name: 2020 WoSC 6
          relative_url: /wosc6
        - name: 2019 WoSC 5
          relative_url: /wosc5
        - name: 2018 WoSC 4
          relative_url: /wosc4
        - name: 2018 WoSC 3
          relative_url: /wosc3
        - name: 2017 WoSC 2
          relative_url: /wosc2
        - name: 2017 WoSC 1
          relative_url: /wosc1
  date_format: "%b %-d, %Y"
  social_links:
    twitter: ""
    github: ""


# Build settings
# theme: jekyll-bootstrap-theme
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
